### ISSUE TITLE
@pawaitemadisoncollege - checkpoint 1 is ready for review

### ISSUE THREAD

**Issue by eemclaughlin** [eemclaughlin/indieProject#1]
@pawaitemadisoncollege - checkpoint 1 is ready for review

**Comment by pawaitemadisoncollege** [comment]
Hi @eemclaughlin! Your work for checkpoint 1 hits the mark!

The problem statement effectively describes the problem and an overview of a unique solution. The user stories, mockups, and flow all provide the right amount of detail to see that this project meets the indie project objective for class, and appears to be scoped to an appropriate size for the semester.  One thing related to the mockups: AWS Cognito can provide the sign-up/sign in dialogs so you likely won't need to create pages for those (just in case you were starting to build jsps already).

While the project plan does not have a lot of detail. I will leave it to you to decide how much detail you need to be successful building the project. It may helpful to break down the individual stories into tasks and list those in the plan or put them into a tool like Trello. 

Journal/time log - Looks to be up-to-date and complete!

Looking forward to seeing progress on this over the coming weeks!!!
