### ISSUE TITLE
Week 6 Ready For Review

### ISSUE THREAD

**Issue by eemclaughlin** [eemclaughlin/indieProject#2]
@pawaitemadisoncollege

### Link Info
IP of AWS Site is: http://indieproject-env.eba-phcxjxhi.us-east-2.elasticbeanstalk.com/

[Link To Site](http://indieproject-env.eba-phcxjxhi.us-east-2.elasticbeanstalk.com/)

### Questions Answered

What were your key learning points/takeaways?
I thought that setting up with AWS would be super complex and difficult.  Without any context, it looks like a lot of stuff but with your guide it was easy.

What challenged you?
The hardest part was just getting the database copied over.

What problems did you solve and what resources did you use to solve them?
Overall the process for this went pretty smooth and my test page from the indie project is working successfully.

### Screenshots

![AwsRunningWithDatabaseData](https://user-images.githubusercontent.com/97905185/193422622-d1cada09-38ae-4949-8bb3-b8434d7ce6d6.png)
![AwsSiteRunningSuccess](https://user-images.githubusercontent.com/97905185/193422623-e6a7ac77-9383-4eab-9e21-248c9504bfce.png)
![BeanstalkAwsGood](https://user-images.githubusercontent.com/97905185/193422624-8dc92c36-6755-4c1c-8938-8a39893505c6.png)

**Comment by pawaitemadisoncollege** [comment]
Wow @eemclaughlin!  It's exciting to see the start of your indie project out on AWS!  I'm glad to hear the documentation was helpful - you are right - the aws ecosystem can be very complex.  Your weekly work submissions show you are keeping ahead of schedule!
