### ISSUE TITLE
Week 5 Ready For Review

### ISSUE THREAD

**Issue by eemclaughlin** [eemclaughlin/indieProject#3]
@pawaitemadisoncollege 

What were your key learning points/takeaways?
- I learned how all the parts start coming together to make an overall more streamlined application.  This would include the testing parts, the dao parts, and the hibernate/database parts.

What challenged you?
- I found this whole exercise to be very difficult.  I worked through the videos a couple times and viewed the documentation but struggled a lot.  The biggest sticking points for me were with integrating the cross testing i.e testing the author using the book test and book using the author tests.   This is mostly pertaining to the insert test.

What problems did you solve and what resources did you use to solve them?
- I was able to integrate the genericdao and get all tests passing using that.  I also got my test jsps running using the genericdao.  It was cool to be able to phase out the daos with with duplicate code.

![Week5ShotOfCoverageAndTests](https://user-images.githubusercontent.com/97905185/193491505-15d845ee-83bc-4f0f-8093-e9b19968d319.png)

**Comment by pawaitemadisoncollege** [comment]
Hi @eemclaughlin!   There is a LOT going on with implementing hibernate with multiple tables/entities; it can be very challenging to wrap our heads around all of it!  A big kudos for getting this implemented in your indie project right away! AND you have the genericDao in there too?! Excellent!

- [ ] I agree that unit testing could be more thorough to ensure all entities and relationships are set up correctly.  I generally recommend one unit test for each entity dao, so you'd have a RecipeDaoTest, UserDaoTest, CookBookDaoTest, etc. 
- [ ] Think about testing the delete scenarios in one-to-many relationships. For example, if a user is deleted, what should happen to their recipes? What if a recipe is deleted? Write tests to make sure whatever should happen, does happen.

Keep up all this great work!!!
