### ISSUE TITLE
Checkpoint 2 ready for review

### ISSUE THREAD

**Issue by eemclaughlin** [eemclaughlin/indieProject#5]
@pawaitemadisoncollege

I think that I meet all the criteria for checkpoint 2.  

Things are a bit of a mess, of course, but all the required parts are working.

**Comment by pawaitemadisoncollege** [comment]
Hi @eemclaughlin Your project work is looking good and achieves checkpoint 2!

**Database designed and created**

- Appears to be well-designed.
- Number of tables and relationships meet the ent java project objectives.
- Your comment on the ERD is correct, some user data will be handled by Cognito. I think you can remove the password column, at least. 

**At least one DAO with full CRUD (create, read, update, delete) implemented with Hibernate. Fully unit tested.**

- Generic dao is implemented and the Recipe is tested! 
- Next steps will be to unit test other entities as you add them to ensure crud is working on those entities as well. I'd recommend one [EntityName]DaoTest for each entity.  
- Relationship testing can be more thorough by testing the delete scenarios. For example, if a Recipe is deleted, what should happen to the user? to the cookbook? Test to make sure what should happen, does happen. 

**Log4J is implemented (no System.out.printlns)**

- No printlns found
-  I noticed logs are in GitHub. This may not be necessary; also be careful that sensitive data is not logged and then pushed to GitHub.

**Other**

-  Looks like a good start with many other aspects of the project, including JSPs. It seems like you are close to hitting checkpoint 3 already. 
- [ ] Are there more specific tasks you can add to the project plan now that you know much more than you did when you first drafted the plan? Cognito? Web Service stuff?
