### ISSUE TITLE
Week 8 ready for review

### ISSUE THREAD

**Issue by eemclaughlin** [eemclaughlin/indieProject#6]
@pawaitemadisoncollege week 8 is complete

What were your key learning points/takeaways?
This was actually the week/lesson I was looking forward to the most.  I think it is really neat to be able to scrape and gather data.

What challenged you?
I forgot that you had that supplementary video for complex services so spent a bit of time trying to get my API working.  Once I watched that one, a lot of stuff made a lot more sense. 

What problems did you solve and what resources did you use to solve them?
One of my tests (to output authors) required even another 'For loop' beyond what you had in your Complex Services video.  It took some brain power to get that to work but it works.

Also, the google books api returns a lot of extra data that I did not need.  It also has ways to filter down that data before it is returned to you.  I spend a bit of time getting my query with the filtering which was fun and challenging.  

![BookApiTestSuccess](https://user-images.githubusercontent.com/97905185/195211728-ba8d3018-6f60-4b3b-b881-e93209bf60bf.png)

**Comment by pawaitemadisoncollege** [comment]
Hey @eemclaughlin! Well, there's nothing like picking one of the most complex of the complex apis here!  Some of those service responses can be sooooo tricky to pick through  - BIG kudos for getting it done! Week 8 signifies the end of the new topics that you need to implement in your indie project, so you hopefully you can find some time and energy to start iterating through your various user stories before the team project begins in a couple weeks. 

I'm certain this is on your radar, but I'd be slacking if I didn't point it out. This method, https://github.com/eemclaughlin/indieProject/blob/bad56d600b25851d2111d8ecbebaa02ffbd69de6/src/main/java/com/ericmclaughlin/persistence/BookApiDao.java#L35,  should eventually have a param to receive the isbn to avoid  hardcoding it: https://github.com/eemclaughlin/indieProject/blob/bad56d600b25851d2111d8ecbebaa02ffbd69de6/src/main/java/com/ericmclaughlin/persistence/BookApiDao.java#L42.  Total nitpick I know, but you didn't leave me much to critique!!!
