### ISSUE TITLE
Checkpoint 3

### ISSUE THREAD

**Issue by eemclaughlin** [eemclaughlin/indieProject#7]
@pawaitemadisoncollege

I believe I have hit the criteria for project 3...  Its a bit of a mess right now but AWS is up and Cognito is applied.  

Once logged in, it dumps you out to the homepage where you see all your recipes (pulled from the database).  Currently, it is setup to always show a test user's recipes (Johnny Cash's) but I do have it working where it shows the recipes of the user that is logged in.

http://recipetracker-env.eba-vhjjf2ef.us-east-2.elasticbeanstalk.com/

**Comment by pawaitemadisoncollege** [comment]
Hi @eemclaughlin! I was able to sign up as a new user and see Johnny's recipes in your deployed app, which hits the mark for Checkpoint 3!

I also took a little time to review some code as well and I noticed a couple items (in addition to those I pointed out in previous issues):

- [ ] It seems like there should be user, cookbook, and tag unit tests to verify all hibernate annotations and relationships are working as expected.
- [ ] We generally want to avoid putting java code in our jsps: https://github.com/eemclaughlin/indieProject/blob/5364ec67fa4f638f339aaaf76ac401971811cfba/src/main/webapp/index.jsp#L10-L12. How else can you handle this?
