### ISSUE TITLE
Midterm Self-Evaluation

### ISSUE THREAD

**Issue by eemclaughlin** [eemclaughlin/indieProject#8]
@pawaitemadisoncollege

Here is my self evaluation for the midterm (little late...)

You should be able to get to it from the link below  or from the readme if the link does not work.

[Link](https://github.com/eemclaughlin/indieProject/blob/816042289a2e3139836a99b6a42a140cb4420b49/DesignDocuments/Self-Evaluations/selfEvaluationMidTerm-22-10-30.md)

**Comment by pawaitemadisoncollege** [comment]
Hi @eemclaughlin! Your self-evaluation level selections and comments are on target: accurately representing where you are in the Enterprise Java journey and what you need to progress.

Moving forward, I recommend reviewing this document regularly  and adding a brief example or summary of how your level of achievement has progressed. I will try to highlight opportunities related to this as well.

With regard to the teamwork and Git/GitHub categories, given your comfort level Git/GitHub, consider serving as "merge coordinator" for your team by proposing and implement a branching and merging strategy.  You may find you can further these skills by assisting less-experience teammate with version control. 

Keep up the solid work!
